# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: meghribe <meghribe@student.42barcelona.co  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/03/28 19:53:01 by meghribe          #+#    #+#              #
#    Updated: 2026/04/22 11:42:21 by meghribe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# https://betterstack.com/community/guides/scaling-docker/docker-compose-getting-started/
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    ports:
      - "9000:9000"
    volumes:
      - wordpress_volume:/CHANGETEHISROUTE

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - mariadb_volume:/CHANGETEHISROUTE

volumes:
  mariadb_volume:
  wordpress_volume:

# https://docs.docker.com/compose/how-tos/networking/
networks:
  inception:
    driver: bridge

