# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: meghribe <meghribe@student.42barcelona.co  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/06/07 00:05:45 by meghribe          #+#    #+#              #
#    Updated: 2026/06/07 00:34:27 by meghribe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

volumes:
  mariadb:
  wordpress:

services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile
  mariadb:
    volumes:
      - mariadb:/./mariadb
    build:
      dockerfile: mariadb/Dockerfile
  wordpress:
    volumes:
      - wordpress:/./wordpress
    build:
      dockerfile: wordpress/Dockerfile
